In [2]:
from data import *

update=Update()
fromSQL=FromSQL()
# fromType=FromType()

In [3]:
# update.downloadAll()
# update.updateAll()
update.singleStockToSQL("TAIEX",'2006-01-01','2022-11-30','TaiwanStockPrice')

get single data:  TAIEX 2006-01-01 2022-11-30 TaiwanStockPrice
update data TAIEX 2006-01-01 2022-11-30 TaiwanStockPrice

In [3]:
fromSQL.allTypeFromSQL()

{'TaiwanStockMonthRevenue': ['revenue'],
 'TaiwanStockPrice': ['Trading_Volume',
  'Trading_money',
  'open',
  'max',
  'min',
  'close',
  'spread',
  'Trading_turnover'],
 'TaiwanStockFinancialStatements': ['OperatingExpenses',
  'IncomeLossFromDiscontinuedOperation',
  'ExtraordinaryItems',
  'CumulativeEffectOfChangesInAccountingPrinciple',
  'EPS',
  'OperatingIncome',
  'PreTaxIncome',
  'TAX',
  'TotalConsolidatedProfitForThePeriod',
  'Revenue',
  'CostOfGoodsSold',
  'GrossProfit',
  'UnrealizedGainFromInterAffiliateAccounts',
  'RealizedGainFromInterAffiliateAccounts',
  'TotalNonbusinessIncome',
  'TotalnonbusinessExpenditure',
  'IncomeBeforeTaxFromContinuingOperations',
  'IncomeFromContinuingOperations',
  '-',
  'NetIncome',
  'NetInterestIncome',
  'ServiceFeeRevenueCommissionNet',
  'NetNonInterestIncome',
  'BadDebts',
  'IncomeAfterTaxFromContinuingOperations',
  'IncomeLossAfterTaxFromDiscontinuedOperation',
  'ExtraordinaryItemsAfterTax',
  'CumulativeEffectOfChangesInAccountingPrincipleAfterTax',
  'IncomeAfterTaxes',
  'AdjustmentItem',
  'ConsolidatedNetIncome',
  'TotalConsolidatedProfitForThePeriodBelongsParentCompany',
  'ConsolidatedNetIncomeAttributed2NoncontrollingInterest',
  'IncomeBeforeIncomeTax',
  'OtherComprehensiveIncomeAfterTax',
  'EquityAttributableToOwnersOfParent',
  'NoncontrollingInterests',
  'Income',
  'Expense',
  '所得稅利益（費用）',
  'OtherComprehensiveIncomeAfterTaxThePeriod',
  'TotalNonoperatingIncomeAndExpense',
  'OtherComprehensiveIncome',
  'UnrealizedGain',
  'RealizedGain',
  'OTHNOE',
  'BadDebtExpenseGuaranteeLiabilityProvisions',
  'TotalConsolidatedProfitForThePeriodAfterTax',
  '呆帳費用及保證責任準備提存（各項提存）',
  'IncomeAfterTax',
  'NetChangeInProvisionsForInsuranceLiabilities',
  'GainsOnInitialRecognitionOfBiologicalAssetsForCurrentPeriod',
  'GainsOnChangesInFairValueLessCosts2SellOfBiologicalAssetsForCurrentPeriod'],
 'TaiwanStockBalanceSheet': ['AccountsPayable_per',
  'AccountsPayableToRelatedParties',
  'AccountsPayableToRelatedParties_per',
  'AccountsReceivableDuefromRelatedPartiesNet',
  'AccountsReceivableDuefromRelatedPartiesNet_per',
  'AccountsReceivableNet_per',
  'BondsPayable',
  'BondsPayable_per',
  'CapitalStock_per',
  'CapitalSurplus_per',
  'CashAndCashEquivalents_per',
  'CurrentAssets_per',
  'CurrentAvailableForSaleFinancialAssets_per',
  'CurrentFinancialAssetsAtFairvalueThroughProfitOrLoss_per',
  'CurrentLiabilities_per',
  'CurrentTaxLiabilities_per',
  'Equity_per',
  'EquityAttributableToOwnersOfParent_per',
  'EquivalentIssueSharesOfAdvanceReceiptsForOrdinaryShare',
  'IntangibleAssets_per',
  'Inventories_per',
  'InvestmentAccountedForUsingEquityMethod_per',
  'Liabilities',
  'Liabilities_per',
  'LongtermBorrowings_per',
  'NoncontrollingInterests_per',
  'NoncurrentAssets_per',
  'NonCurrentAvailableForSaleFinancialAssets_per',
  'NoncurrentLiabilities_per',
  'NumberOfSharesInEntityHeldByEntityAndByItsSubsidiaries',
  'OrdinaryShare_per',
  'OtherCurrentAssets_per',
  'OtherCurrentLiabilities_per',
  'OtherEquityInterest_per',
  'OtherNoncurrentAssets_per',
  'OtherNoncurrentLiabilities',
  'OtherNoncurrentLiabilities_per',
  'OtherPayables_per',
  'OtherReceivablesDueFromRelatedParties_per',
  'PropertyPlantAndEquipment_per',
  'RetainedEarnings_per',
  'ShorttermBorrowings_per',
  'TotalAssets_per',
  'CashAndCashEquivalents',
  'CurrentFinancialAssetsAtFairvalueThroughProfitOrLoss',
  'BillsReceivableNet',
  'BillsReceivableNet_per',
  'Prepayments',
  'Prepayments_per',
  'CurrentAvailableForSaleFinancialAssets',
  'AccountsReceivableNet',
  'OtherReceivablesDueFromRelatedParties',
  'Inventories',
  'OtherCurrentAssets',
  'CurrentAssets',
  'InvestmentAccountedForUsingEquityMethod',
  'PropertyPlantAndEquipment',
  'IntangibleAssets',
  'OtherNoncurrentAssets',
  'NoncurrentAssets',
  'TotalAssets',
  'ShorttermBorrowings',
  'AccountsPayable',
  'OtherPayables',
  'CurrentTaxLiabilities',
  'OtherCurrentLiabilities',
  'CurrentLiabilities',
  'LongtermBorrowings',
  'NoncurrentLiabilities',
  'OrdinaryShare',
  'CapitalStock',
  'CapitalSurplus',
  'RetainedEarnings',
  'OtherEquityInterest',
  'EquityAttributableToOwnersOfParent',
  'NoncontrollingInterests',
  'Equity',
  'NonCurrentAvailableForSaleFinancialAssets',
  'CurrentFinancialLiabilitiesAtFairValueThroughProfitOrLoss',
  'CurrentFinancialLiabilitiesAtFairValueThroughProfitOrLoss_per',
  'CurrentProvisions',
  'CurrentProvisions_per',
  'DeferredTaxAssets',
  'DeferredTaxAssets_per',
  'LegalReserve_per',
  'OtherReceivable',
  'OtherReceivable_per',
  'UnappropriatedRetainedEarningsAaccumulatedDeficit',
  'UnappropriatedRetainedEarningsAaccumulatedDeficit_per',
  'LegalReserve',
  'CapitalSurplusAdditionalPaidInCapital',
  'CapitalSurplusAdditionalPaidInCapital_per',
  'ConstructionContractReceivable',
  'ConstructionContractReceivable_per',
  'CurrentDerivativeFinancialLiabilitiesForHedging',
  'CurrentDerivativeFinancialLiabilitiesForHedging_per',
  'CurrentHeldToMaturityFinancialAssets',
  'CurrentHeldToMaturityFinancialAssets_per',
  'FinancialAssetsAtFairvalueThroughOtherComprehensiveIncome',
  'FinancialAssetsAtFairvalueThroughOtherComprehensiveIncome_per',
  'CapitalSurplusChangesInEquityOfAssociatesAndJointVenturesAccountedForUsingEquityMethod',
  'CapitalSurplusChangesInEquityOfAssociatesAndJointVenturesAccountedForUsingEquityMethod_per',
  'CapitalSurplusChangesInOwnershipInterestsInSubsidiaries',
  'CapitalSurplusChangesInOwnershipInterestsInSubsidiaries_per',
  'CapitalSurplusDonatedAssetsReceived',
  'CapitalSurplusDonatedAssetsReceived_per',
  'CapitalSurplusNetAssetsFromMerger_per',
  'CapitalSurplusNetAssetsFromMerger',
  'TotalLiabilitiesEquity_per',
  'TotalLiabilitiesEquity',
  'CurrentIncomeTaxAssets',
  'CurrentIncomeTaxAssets_per',
  'HedgingAinancialAssets',
  'HedgingAinancialAssets_per',
  'FinancialAssetsAtAmortizedCost',
  'FinancialAssetsAtAmortizedCost_per'],
 'TaiwanStockCashFlowsStatement': ['TotalIncomeLossItems',
  'CashFlowsProvidedFromFinancingActivities',
  'DecreaseInShortTermLoans',
  'OtherNonCurrentLiabilitiesDecrease',
  'InterestIncome',
  'CashReceivedThroughOperations',
  'PayTheInterest',
  'InventoryIncrease',
  'CashBalancesIncrease',
  'ReceivableIncrease',
  'CashBalancesBeginningOfPeriod',
  'RepaymentOfLongTermDebt',
  'AmountDueToRelatedParties',
  'InterestExpense',
  'AccountsPayable',
  'IncomeBeforeIncomeTaxFromContinuingOperations',
  'PropertyAndPlantAndEquipment',
  'NetIncomeBeforeTax',
  'CashFlowsFromOperatingActivities',
  'CashProvidedByInvestingActivities',
  'CashBalancesEndOfPeriod',
  'OtherNonCurrentLiabilitiesIncrease',
  'Depreciation',
  'AmortizationExpense',
  'ProceedsFromLongTermDebt',
  'RedemptionOfBonds',
  'UnrealizedGain',
  'DecreaseInDepositDeposit',
  'RealizedGain',
  'HedgingFinancialLiabilities',
  'RentalPrincipalRepayments']}

In [3]:
fromType.data("close")

stock_id,0050,0051,0052,0053,0055,0056,0057,0061,006201,006203,...,PaperPulp,Plastics,Rubber,Semiconductor,ShippingTransportation,TAIEX,TPEx,Textiles,Tourism,TradingConsumersGoods
date,,,,,,,,,,,,,,,,,,,,,
2006-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-08,113.25,52.50,96.70,54.30,21.76,25.29,80.95,18.74,15.91,55.10,...,294.87,240.06,233.34,317.24,155.82,14553.04,187.85,587.55,117.26,281.51
2022-12-09,115.00,52.55,98.30,55.05,21.88,25.51,81.90,18.82,15.97,55.70,...,294.86,241.23,236.00,323.74,158.92,14705.43,188.14,590.09,117.42,283.14
2022-12-12,113.90,52.30,97.15,54.45,21.76,25.50,81.20,18.68,15.82,55.20,...,293.41,239.87,234.96,319.67,157.55,14612.59,187.43,585.85,116.45,280.58
2022-12-13,113.40,52.30,96.70,54.10,21.75,25.53,80.70,18.65,15.70,55.05,...,295.71,238.46,232.54,317.59,158.40,14522.96,186.29,576.81,115.75,278.18
2022-12-14,114.80,53.00,98.15,54.90,21.90,25.68,81.75,18.73,16.01,55.70,...,296.00,241.73,234.88,323.91,157.77,14739.36,189.41,582.31,116.98,283.34

In [2]:
fromSQL.datasetFromSQL('TaiwanStockFinancialStatements')

DatabaseError: Execution failed on sql 'select * from 'close' ': no such table: close