In [1]:
from monthData import *

md=MonthData()

In [2]:
from seasonData import *

sd=StatementData()

In [3]:
from data import *

ft=FromType()

In [14]:
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [4]:
price=ft.data('close')

In [5]:
cond1=(md.nMonthYearIncrease(3)>md.nMonthYearIncrease(9))

In [10]:
cond1

stock_id,1101,1102,1103,1104,1107,1108,1109,1110,1201,1203,...,9944,9945,9946,9949,9950,9951,9955,9958,9960,9962
date,,,,,,,,,,,,,,,,,,,,,
2005-12-10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2006-01-10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2006-02-10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2006-03-10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2006-04-10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-07-10,True,False,True,True,False,True,True,False,False,True,...,False,False,True,True,True,True,True,False,True,False
2022-08-10,True,False,True,True,False,True,True,False,True,False,...,True,False,True,True,True,True,True,False,True,False
2022-09-10,True,False,True,True,False,True,True,True,True,False,...,True,False,False,True,False,True,True,False,False,False
2022-10-10,True,False,True,True,False,True,True,True,True,True,...,True,False,False,True,False,True,False,False,True,False
2022-11-10,True,False,True,False,False,True,True,True,False,True,...,True,True,False,False,False,True,False,True,True,False

In [6]:
priceReindex=price.reindex(cond1.index,method="ffill")

In [7]:
priceReindex

stock_id,0050,0051,0052,0053,0055,0056,0057,0061,006201,006203,...,PaperPulp,Plastics,Rubber,Semiconductor,ShippingTransportation,TAIEX,TPEx,Textiles,Tourism,TradingConsumersGoods
date,,,,,,,,,,,,,,,,,,,,,
2005-12-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6264.36,NaN,NaN,NaN,NaN
2006-01-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6707.40,NaN,NaN,NaN,NaN
2006-02-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6594.92,NaN,NaN,NaN,NaN
2006-03-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6490.68,NaN,NaN,NaN,NaN
2006-04-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6780.64,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-07-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,14464.53,NaN,NaN,NaN,NaN
2022-08-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,14939.02,NaN,NaN,NaN,NaN
2022-09-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,14583.42,NaN,NaN,NaN,NaN
2022-10-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,13702.28,NaN,NaN,NaN,NaN
2022-11-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,13503.76,NaN,NaN,NaN,NaN

In [1]:
(priceReindex[cond1])['2330']

NameError: name 'priceReindex' is not defined

In [26]:
cond2=((sd.dt.nPeriodIncrease(4,incomeAfterTax,4)>25).iloc[-1]&((sd.dt.nPeriodIncrease(4,incomeAfterTax,4)>25).iloc[-5])&((sd.dt.nPeriodIncrease(4,incomeAfterTax,4)>25).iloc[-9]))

In [2]:
incomeAfterTax=sd.typeData('IncomeAfterTax')

In [3]:
incomeAfterTax

stock_id,000018,000019,000020,000022,000024,000025,000026,000027,000055,000060,...,A00013,A00014,A00025,A00026,A00037,A00041,A00043,A00047,A00048,B00295
date,,,,,,,,,,,,,,,,,,,,,
2006-05-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-08-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-11-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2005-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2007-05-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-11-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-05-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-08-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-11-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN