In [1]:
from dayData import *

dayData=DayData()

In [5]:
dm=DateManage()

In [3]:
close=dayData.price.pivot_table(index='date',columns='stock_id',values='close')
close

stock_id,0050,0051,0052,0053,0055,0056,0057,0061,006201,006203,...,PaperPulp,Plastics,Rubber,Semiconductor,ShippingTransportation,TAIEX,TPEx,Textiles,Tourism,TradingConsumersGoods
date,,,,,,,,,,,,,,,,,,,,,
1999-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6152.43,NaN,NaN,NaN,NaN
1999-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6199.91,NaN,NaN,NaN,NaN
1999-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6404.31,NaN,NaN,NaN,NaN
1999-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6421.75,NaN,NaN,NaN,NaN
1999-01-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6406.99,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-12-08,113.25,52.50,96.70,54.30,21.76,25.29,80.95,18.74,15.91,55.10,...,294.87,240.06,233.34,317.24,155.82,14553.04,187.85,587.55,117.26,281.51
2022-12-09,115.00,52.55,98.30,55.05,21.88,25.51,81.90,18.82,15.97,55.70,...,294.86,241.23,236.00,323.74,158.92,14705.43,188.14,590.09,117.42,283.14
2022-12-12,113.90,52.30,97.15,54.45,21.76,25.50,81.20,18.68,15.82,55.20,...,293.41,239.87,234.96,319.67,157.55,14612.59,187.43,585.85,116.45,280.58
2022-12-13,113.40,52.30,96.70,54.10,21.75,25.53,80.70,18.65,15.70,55.05,...,295.71,238.46,232.54,317.59,158.40,14522.96,186.29,576.81,115.75,278.18
2022-12-14,114.80,53.00,98.15,54.90,21.90,25.68,81.75,18.73,16.01,55.70,...,296.00,241.73,234.88,323.91,157.77,14739.36,189.41,582.31,116.98,283.34

In [16]:
priceIncrease=close.loc['2022-12-14']/close.loc['2006-01-11']-1

In [20]:
priceIncrease[priceIncrease.notna()].sort_values()

stock_id
4419    -1.000000
3115    -1.000000
6221    -1.000000
5205    -1.000000
3067    -1.000000
          ...
3004    36.250000
9906    39.180180
5306    40.232877
9931          inf
2539          inf
Length: 954, dtype: float64